ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 18, in index
    return render(request, "index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
WARNING:django.request:Not Found: /preview
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 30, in get
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 30, in get
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 28, in get
    with open(os.path.join(settings.REACT_APP_DIR, 'build', 'index.html')) as f:
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'REACT_APP_DIR'
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /map
WARNING:django.request:Not Found: /map
WARNING:django.request:Not Found: /map
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /map
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
ERROR:django.request:Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 43, in profile
    data = json.loads(request.GET.get('data'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /font-awesome/css/font-awesome.min.css
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /preview
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): //api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Not Found: /preview/
WARNING:django.request:Not Found: /preview/
WARNING:django.request:Not Found: /preview/
WARNING:django.request:Not Found: /preview/
WARNING:django.request:Not Found: /preview/
WARNING:django.request:Not Found: /preview/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /preview/api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
WARNING:django.request:Method Not Allowed (POST): /api/login/
DEBUG:root:it's routing
ERROR:django.request:Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view messenger.views.FrontendAppView didn't return an HttpResponse object. It returned None instead.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.google.com
DEBUG:urllib3.connectionpool:https://maps.google.com:443 "GET /maps/api/geocode/json?language=&region=&bounds=&components=&address=new+york&sensor=false HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.google.com
DEBUG:urllib3.connectionpool:https://maps.google.com:443 "GET /maps/api/geocode/json?language=&region=&bounds=&components=&address=boston&sensor=false HTTP/1.1" 200 None
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 140, in friends
    friend_obj_friends = Friends.objs.get(user_owner=friend_obj)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Friends matching query does not exist.
ERROR:django.request:Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /admin/messenger/user/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /admin/messenger/user/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /admin/messenger/user/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /admin/messenger/user/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /admin/messenger/user/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/Library/Python/2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 386, in __init__
    self.hashed_files = self.load_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 396, in load_manifest
    content = self.read_manifest()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 390, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 28, in get
    with open(os.path.join(settings.REACT_APP_DIR, 'build', 'index.html')) as f:
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'REACT_APP_DIR'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 137, in friends
    friend_obj_friends = Friends.objs.get(user_owner=friend_obj)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Friends matching query does not exist.
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 137, in friends
    friend_obj_friends = Friends.objs.get(user_owner=friend_obj)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Friends matching query does not exist.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 30, in get
    with open(os.path.join(settings.STATIC_ROOT, 'index.html')) as f:
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 145, in friends
    friend_obj = User.objs.get(user_id=int(friend_id))
TypeError: int() argument must be a string or a number, not 'list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
DEBUG:root:[[]]
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 146, in friends
    friend_obj = User.objs.get(user_id=int(friend_id))
TypeError: int() argument must be a string or a number, not 'list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
DEBUG:root:[]
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.values_list('user_id', flat=True)})
AttributeError: 'Friends' object has no attribute 'values_list'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 123, in friends
    return JsonResponse({'friends': user_owner_friends.users.values_list('user_id', flat=True)})
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <QuerySet [108939996377065, 1111111111, 99999, 88888, 77777]> is not JSON serializable
WARNING:django.request:Not Found: /null
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /api/friends/
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/messenger/views.py", line 153, in friends
    return JsonResponse({'friends': user_owner_friends.as_json()})
  File "/Users/ethan/Desktop/staywme/staywme/messenger/models.py", line 57, in as_json
    question1=f.questions1,
AttributeError: 'User' object has no attribute 'questions1'
ERROR:django.request:Internal Server Error: /messenger
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 36, in process_view
    retval = super(_EnsureCsrfCookie, self).process_view(request, callback, callback_args, callback_kwargs)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 208, in process_view
    csrf_token = self._get_token(request)
  File "/Users/ethan/Desktop/staywme/staywme/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 177, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'FrontendAppView' object has no attribute 'COOKIES'
